/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 Barry.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function BarryModel(props) {
  const { nodes, materials } = useGLTF('/Male/Male/Barry/Barry.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.CC_Base_Body008.geometry} material={materials['Std_Skin_Head.005']} />
        <mesh geometry={nodes.CC_Base_Body008_1.geometry} material={materials['Std_Skin_Body.005']} />
        <mesh geometry={nodes.CC_Base_Body008_2.geometry} material={materials['Std_Skin_Arm.005']} />
        <mesh geometry={nodes.CC_Base_Body008_3.geometry} material={materials['Std_Skin_Leg.005']} />
        <mesh geometry={nodes.CC_Base_Body008_4.geometry} material={materials['Std_Nails.005']} />
        <mesh geometry={nodes.CC_Base_Body008_5.geometry} material={materials['Std_Eyelash.005']} />
        <mesh geometry={nodes.CC_Base_Body008_6.geometry} material={materials['Basic_T_shirts.005']} />
        <mesh geometry={nodes.CC_Base_Body008_7.geometry} material={materials['Std_Eye_R.005']} />
        <mesh geometry={nodes.CC_Base_Body008_8.geometry} material={materials['Std_Cornea_R.005']} />
        <mesh geometry={nodes.CC_Base_Body008_9.geometry} material={materials['Std_Eye_L.005']} />
        <mesh geometry={nodes.CC_Base_Body008_10.geometry} material={materials['Std_Cornea_L.005']} />
        <mesh geometry={nodes.CC_Base_Body008_11.geometry} material={materials['Std_Eye_Occlusion_R.005']} />
        <mesh geometry={nodes.CC_Base_Body008_12.geometry} material={materials['Std_Eye_Occlusion_L.005']} />
        <mesh geometry={nodes.CC_Base_Body008_13.geometry} material={materials['Std_Tearline_R.005']} />
        <mesh geometry={nodes.CC_Base_Body008_14.geometry} material={materials['Std_Tearline_L.005']} />
        <mesh geometry={nodes.CC_Base_Body008_15.geometry} material={materials['Std_Upper_Teeth.005']} />
        <mesh geometry={nodes.CC_Base_Body008_16.geometry} material={materials['Std_Lower_Teeth.005']} />
        <mesh geometry={nodes.CC_Base_Body008_17.geometry} material={materials['Std_Tongue.005']} />
        <mesh geometry={nodes.CC_Base_Body008_18.geometry} material={materials['Beard_Transparency.001']} />
        <mesh geometry={nodes.CC_Base_Body008_19.geometry} material={materials.Male_Bushy_Transparency} />
        <mesh geometry={nodes.CC_Base_Body008_20.geometry} material={materials.Male_Bushy_Base_Transparency} />
        <mesh geometry={nodes.CC_Base_Body008_21.geometry} material={materials['Beard_Transparency.003']} />
        <mesh geometry={nodes.CC_Base_Body008_22.geometry} material={materials['Hair_Transparency.012']} />
        <mesh geometry={nodes.CC_Base_Body008_23.geometry} material={materials['Scalp_Transparency.007']} />
        <mesh geometry={nodes.CC_Base_Body008_24.geometry} material={materials.Beard_Transparency} />
        <mesh geometry={nodes.CC_Base_Body008_25.geometry} material={materials['Slim_Jeans.002']} />
        <mesh geometry={nodes.CC_Base_Body008_26.geometry} material={materials['Beard_Transparency.002']} />
        <mesh geometry={nodes.CC_Base_Body008_27.geometry} material={materials['Sport_sneakers.005']} />
      </group>
    </group>
  )
}

useGLTF.preload('/Barry.glb')
