/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 Max.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function MaxModel(props) {
  const { nodes, materials } = useGLTF('/Male/Male/Max/Max.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.CC_Base_Body006.geometry} material={materials['Std_Skin_Head.004']} />
        <mesh geometry={nodes.CC_Base_Body006_1.geometry} material={materials['Std_Skin_Body.004']} />
        <mesh geometry={nodes.CC_Base_Body006_2.geometry} material={materials['Std_Skin_Arm.004']} />
        <mesh geometry={nodes.CC_Base_Body006_3.geometry} material={materials['Std_Skin_Leg.004']} />
        <mesh geometry={nodes.CC_Base_Body006_4.geometry} material={materials['Std_Nails.004']} />
        <mesh geometry={nodes.CC_Base_Body006_5.geometry} material={materials['Std_Eyelash.004']} />
        <mesh geometry={nodes.CC_Base_Body006_6.geometry} material={materials['Basic_T_shirts.004']} />
        <mesh geometry={nodes.CC_Base_Body006_7.geometry} material={materials['Std_Eye_R.004']} />
        <mesh geometry={nodes.CC_Base_Body006_8.geometry} material={materials['Std_Cornea_R.004']} />
        <mesh geometry={nodes.CC_Base_Body006_9.geometry} material={materials['Std_Eye_L.004']} />
        <mesh geometry={nodes.CC_Base_Body006_10.geometry} material={materials['Std_Cornea_L.004']} />
        <mesh geometry={nodes.CC_Base_Body006_11.geometry} material={materials['Std_Eye_Occlusion_R.004']} />
        <mesh geometry={nodes.CC_Base_Body006_12.geometry} material={materials['Std_Eye_Occlusion_L.004']} />
        <mesh geometry={nodes.CC_Base_Body006_13.geometry} material={materials['Std_Tearline_R.004']} />
        <mesh geometry={nodes.CC_Base_Body006_14.geometry} material={materials['Std_Tearline_L.004']} />
        <mesh geometry={nodes.CC_Base_Body006_15.geometry} material={materials['Std_Upper_Teeth.004']} />
        <mesh geometry={nodes.CC_Base_Body006_16.geometry} material={materials['Std_Lower_Teeth.004']} />
        <mesh geometry={nodes.CC_Base_Body006_17.geometry} material={materials['Std_Tongue.004']} />
        <mesh geometry={nodes.CC_Base_Body006_18.geometry} material={materials['Hair_Transparency.011']} />
        <mesh geometry={nodes.CC_Base_Body006_19.geometry} material={materials['Scalp_Transparency.006']} />
        <mesh geometry={nodes.CC_Base_Body006_20.geometry} material={materials['Hair_Transparency.010']} />
        <mesh geometry={nodes.CC_Base_Body006_21.geometry} material={materials['Slim_Jeans.001']} />
        <mesh geometry={nodes.CC_Base_Body006_22.geometry} material={materials['Sport_sneakers.004']} />
        <mesh geometry={nodes.CC_Base_Body006_23.geometry} material={materials['Scalp_Transparency.005']} />
        <mesh geometry={nodes.CC_Base_Body006_24.geometry} material={materials['Hair_Transparency.009']} />
      </group>
    </group>
  )
}

useGLTF.preload('/Max.glb')
