/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 John.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function JohnModel(props) {
  const { nodes, materials } = useGLTF('/John.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.CC_Base_Body004.geometry} material={materials['Std_Skin_Head.003']} />
        <mesh geometry={nodes.CC_Base_Body004_1.geometry} material={materials['Std_Skin_Body.003']} />
        <mesh geometry={nodes.CC_Base_Body004_2.geometry} material={materials['Std_Skin_Arm.003']} />
        <mesh geometry={nodes.CC_Base_Body004_3.geometry} material={materials['Std_Skin_Leg.003']} />
        <mesh geometry={nodes.CC_Base_Body004_4.geometry} material={materials['Std_Nails.003']} />
        <mesh geometry={nodes.CC_Base_Body004_5.geometry} material={materials['Std_Eyelash.003']} />
        <mesh geometry={nodes.CC_Base_Body004_6.geometry} material={materials['Sport_sneakers.003']} />
        <mesh geometry={nodes.CC_Base_Body004_7.geometry} material={materials['Basic_T_shirts.003']} />
        <mesh geometry={nodes.CC_Base_Body004_8.geometry} material={materials['Std_Eye_Occlusion_R.003']} />
        <mesh geometry={nodes.CC_Base_Body004_9.geometry} material={materials['Std_Eye_Occlusion_L.003']} />
        <mesh geometry={nodes.CC_Base_Body004_10.geometry} material={materials['Std_Tongue.003']} />
        <mesh geometry={nodes.CC_Base_Body004_11.geometry} material={materials['Std_Eye_R.003']} />
        <mesh geometry={nodes.CC_Base_Body004_12.geometry} material={materials['Std_Cornea_R.003']} />
        <mesh geometry={nodes.CC_Base_Body004_13.geometry} material={materials['Std_Eye_L.003']} />
        <mesh geometry={nodes.CC_Base_Body004_14.geometry} material={materials['Std_Cornea_L.003']} />
        <mesh geometry={nodes.CC_Base_Body004_15.geometry} material={materials.Slim_Jeans} />
        <mesh geometry={nodes.CC_Base_Body004_16.geometry} material={materials['Hair_Transparency.008']} />
        <mesh geometry={nodes.CC_Base_Body004_17.geometry} material={materials['Scalp_Transparency.004']} />
        <mesh geometry={nodes.CC_Base_Body004_18.geometry} material={materials['Std_Tearline_R.003']} />
        <mesh geometry={nodes.CC_Base_Body004_19.geometry} material={materials['Std_Tearline_L.003']} />
        <mesh geometry={nodes.CC_Base_Body004_20.geometry} material={materials['Std_Upper_Teeth.003']} />
        <mesh geometry={nodes.CC_Base_Body004_21.geometry} material={materials['Std_Lower_Teeth.003']} />
      </group>
    </group>
  )
}

useGLTF.preload('/John.glb')
