/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 Shifa.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function ShifaModel(props) {
  const { nodes, materials } = useGLTF('/Shifa.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.CC_Base_Body002.geometry} material={materials['Std_Skin_Head.002']} />
        <mesh geometry={nodes.CC_Base_Body002_1.geometry} material={materials['Std_Skin_Body.002']} />
        <mesh geometry={nodes.CC_Base_Body002_2.geometry} material={materials['Std_Skin_Arm.002']} />
        <mesh geometry={nodes.CC_Base_Body002_3.geometry} material={materials['Std_Skin_Leg.002']} />
        <mesh geometry={nodes.CC_Base_Body002_4.geometry} material={materials['Std_Nails.002']} />
        <mesh geometry={nodes.CC_Base_Body002_5.geometry} material={materials['Std_Eyelash.002']} />
        <mesh geometry={nodes.CC_Base_Body002_6.geometry} material={materials['Basic_T_shirts.002']} />
        <mesh geometry={nodes.CC_Base_Body002_7.geometry} material={materials['Std_Eye_R.002']} />
        <mesh geometry={nodes.CC_Base_Body002_8.geometry} material={materials['Std_Cornea_R.002']} />
        <mesh geometry={nodes.CC_Base_Body002_9.geometry} material={materials['Std_Eye_L.002']} />
        <mesh geometry={nodes.CC_Base_Body002_10.geometry} material={materials['Std_Cornea_L.002']} />
        <mesh geometry={nodes.CC_Base_Body002_11.geometry} material={materials['Std_Eye_Occlusion_R.002']} />
        <mesh geometry={nodes.CC_Base_Body002_12.geometry} material={materials['Std_Eye_Occlusion_L.002']} />
        <mesh geometry={nodes.CC_Base_Body002_13.geometry} material={materials['Std_Tearline_R.002']} />
        <mesh geometry={nodes.CC_Base_Body002_14.geometry} material={materials['Std_Tearline_L.002']} />
        <mesh geometry={nodes.CC_Base_Body002_15.geometry} material={materials['Std_Upper_Teeth.002']} />
        <mesh geometry={nodes.CC_Base_Body002_16.geometry} material={materials['Std_Lower_Teeth.002']} />
        <mesh geometry={nodes.CC_Base_Body002_17.geometry} material={materials['Std_Tongue.002']} />
        <mesh geometry={nodes.CC_Base_Body002_18.geometry} material={materials['Hair_Transparency.006']} />
        <mesh geometry={nodes.CC_Base_Body002_19.geometry} material={materials['Hair_Transparency.005']} />
        <mesh geometry={nodes.CC_Base_Body002_20.geometry} material={materials['Scalp_Transparency.003']} />
        <mesh geometry={nodes.CC_Base_Body002_21.geometry} material={materials['Rocker_Jeans.002']} />
        <mesh geometry={nodes.CC_Base_Body002_22.geometry} material={materials['Hair_Transparency.007']} />
        <mesh geometry={nodes.CC_Base_Body002_23.geometry} material={materials['BabyHair_Transparency.001']} />
        <mesh geometry={nodes.CC_Base_Body002_24.geometry} material={materials['Sport_sneakers.002']} />
      </group>
    </group>
  )
}

useGLTF.preload('/Shifa.glb')
