/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 Ella.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function EllaModel(props) {
  const { nodes, materials } = useGLTF('/Female/Ella/Ella.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.CC_Base_Body001.geometry} material={materials['Std_Skin_Head.001']} />
        <mesh geometry={nodes.CC_Base_Body001_1.geometry} material={materials['Std_Skin_Body.001']} />
        <mesh geometry={nodes.CC_Base_Body001_2.geometry} material={materials['Std_Skin_Arm.001']} />
        <mesh geometry={nodes.CC_Base_Body001_3.geometry} material={materials['Std_Skin_Leg.001']} />
        <mesh geometry={nodes.CC_Base_Body001_4.geometry} material={materials['Std_Nails.001']} />
        <mesh geometry={nodes.CC_Base_Body001_5.geometry} material={materials['Std_Eyelash.001']} />
        <mesh geometry={nodes.CC_Base_Body001_6.geometry} material={materials['Basic_T_shirts.001']} />
        <mesh geometry={nodes.CC_Base_Body001_7.geometry} material={materials['Std_Eye_R.001']} />
        <mesh geometry={nodes.CC_Base_Body001_8.geometry} material={materials['Std_Cornea_R.001']} />
        <mesh geometry={nodes.CC_Base_Body001_9.geometry} material={materials['Std_Eye_L.001']} />
        <mesh geometry={nodes.CC_Base_Body001_10.geometry} material={materials['Std_Cornea_L.001']} />
        <mesh geometry={nodes.CC_Base_Body001_11.geometry} material={materials['Std_Eye_Occlusion_R.001']} />
        <mesh geometry={nodes.CC_Base_Body001_12.geometry} material={materials['Std_Eye_Occlusion_L.001']} />
        <mesh geometry={nodes.CC_Base_Body001_13.geometry} material={materials['Std_Tearline_R.001']} />
        <mesh geometry={nodes.CC_Base_Body001_14.geometry} material={materials['Std_Tearline_L.001']} />
        <mesh geometry={nodes.CC_Base_Body001_15.geometry} material={materials['Std_Upper_Teeth.001']} />
        <mesh geometry={nodes.CC_Base_Body001_16.geometry} material={materials['Std_Lower_Teeth.001']} />
        <mesh geometry={nodes.CC_Base_Body001_17.geometry} material={materials['Std_Tongue.001']} />
        <mesh geometry={nodes.CC_Base_Body001_18.geometry} material={materials['Hair_Transparency.003']} />
        <mesh geometry={nodes.CC_Base_Body001_19.geometry} material={materials['Scalp_Transparency.001']} />
        <mesh geometry={nodes.CC_Base_Body001_20.geometry} material={materials['Rocker_Jeans.001']} />
        <mesh geometry={nodes.CC_Base_Body001_21.geometry} material={materials['Hair_Transparency.002']} />
        <mesh geometry={nodes.CC_Base_Body001_22.geometry} material={materials.BabyHair_Transparency} />
        <mesh geometry={nodes.CC_Base_Body001_23.geometry} material={materials['Sport_sneakers.001']} />
        <mesh geometry={nodes.CC_Base_Body001_24.geometry} material={materials['Hair_Transparency.004']} />
      </group>
    </group>
  )
}

useGLTF.preload('/Ella.glb')
